### ISSUE TITLE
Features Wanted

### ISSUE THREAD

**Issue by Aeterrno-Amora** [nocrizwang/OIer#10]
### Search by functions

更喜欢zzq那种填充谓词函数来自定义高级检索的功能。
方便快捷，相当于自动同时支持单次搜多人、搜年龄段、分数段等丰富功能。
且对OIer极其友好。

### Display Styles

预览列表应该添加显示“学校”一栏。

![image](https://user-images.githubusercontent.com/37094308/48756914-ff498e80-ecd5-11e8-9959-112d229c90ff.png)

### Other Stuff

另外希望把双线条换成单线条，列表更紧凑一些。展开的行留够空即可，收起的行应该更紧凑些。

为什么普通搜索不能回车发起搜索啊难受qwq

**Comment by nocrizwang** [comment]
我尝试在12月之前搞一搞吧，感谢您的建议

**Comment by Aeterrno-Amora** [comment]
好的谢谢。最近使用中又发现一些可以改进的地方qwq

### Searching

![cdqz](https://user-images.githubusercontent.com/37094308/48945024-dccca500-ef63-11e8-9049-a5497a6c0948.png)

这个考虑得很周到，但是如果能用在搜索上就更好了。现在搜“成都七中”搜不出填“成都市第七中学”的。
这功能在大框框搜索中可能比较难实现，可以只在高级搜索的“学校”框中实现。比如先拿搜索串跟学校列表匹配，得出所有可能学校的id。。。

大部分搜索都希望查找现役选手。可以考虑把年级改成按年级区间筛选。

### Ranking

感觉现在的排序效果还没有原来zzq的好QAQ。比如说：

![jmr](https://user-images.githubusercontent.com/37094308/48966133-03dbb300-f006-11e8-984c-8fcb5fb5c020.jpg)

jmr靠一次普及组AK就可以排在集训队yfz前面，显然极不合理。
而在zzq那里，jmr评分12.55，yfz评分116.85

**Comment by nocrizwang** [comment]
搜索学校之前想过要搞了……一直鸽掉了
有时间会做的

**Comment by nocrizwang** [comment]
另外这个人的排名现在还很科幻，和学校排名用的不是同一个算法，那个还是比较靠谱的
