### ISSUE TITLE
更适用于数据存储的仓库

### ISSUE THREAD

**Issue by frankli0324** [nocrizwang/OIer#100]
`OIer` 项目大体上可以分为两部分：一个是用于向用户展示数据的前后端代码部分，另一部分是持续更新的OIer信息部分。

Git非常适用于对代码进行版本追踪，但是数据一直并没有很好的版本追踪方式

https://github.com/dolthub/dolt
dolt是专门用于对数据进行版本追踪的工具(官网https://dolthub.com) ，私以为是更适合维护数据部分的平台。

**Comment by nocrizwang** [comment]
您说的很有道理
