### ISSUE TITLE
学校合并：福州第一中学

### ISSUE THREAD

**Issue by fqyzwyc** [nocrizwang/OIer#119]
[福州一中在OIerDb中的页面](https://bytew.net/OIer/school.html?schoolid=741479984)
合并错误的学校：
1.[福建省福清第一中学](https://baike.baidu.com/item/%E7%A6%8F%E5%BB%BA%E7%9C%81%E7%A6%8F%E6%B8%85%E7%AC%AC%E4%B8%80%E4%B8%AD%E5%AD%A6)，又名福清一中，地址在福州市下属县级市福清市。
2.[福建省连江县第一中学](https://baike.baidu.com/item/%E7%A6%8F%E5%BB%BA%E7%9C%81%E8%BF%9E%E6%B1%9F%E7%AC%AC%E4%B8%80%E4%B8%AD%E5%AD%A6/18722929)，又名连江一中，位于福州市连江县。

**Comment by nocrizwang** [comment]
此问题已解决
