### ISSUE TITLE
如果有空请帮我合并一下数据，谢谢！

### ISSUE THREAD

**Issue by ceciliazyx** [nocrizwang/OIer#120]
![9631632927104_ pic](https://user-images.githubusercontent.com/91618337/135293925-c32c33f7-599c-49ef-9f31-0e624795c7a9.jpg)

这两个都是我，如果有可能，能帮忙合并在一起么，谢谢啦！

**Comment by ceciliazyx** [comment]
数据没有改变啊，还是两个人……

**Comment by nocrizwang** [comment]
此问题已解决
