### ISSUE TITLE
建议能更新初赛认证

### ISSUE THREAD

**Issue by HappyCodeHC** [nocrizwang/OIer#123]
本人CSP-J1准考证号BJ-00656，成绩47.5，2=。CSP-S1准考证号BJ-00296，成绩31，3=。我太蒟了，初赛都没过……

**Comment by HappyCodeHC** [comment]
抢到 Issues#123 祭

**Comment by nocrizwang** [comment]
抱歉，noi.cn上没有不更

**Comment by HappyCodeHC** [comment]
@nocrizwang 可以在[各省新闻](https://noi.cn/gs/xw/)里查到初赛成绩和是否过初赛
