### ISSUE TITLE
需要修正数据

### ISSUE THREAD

**Issue by lizhirui** [nocrizwang/OIer#124]
李志锐，NOIP2013普及组一等奖，130分，石油大学（华东）附中，初中-2011，实际上应该是初中-2010，我初中是四年制。

另，缺少我的NOIP2014提高组（高中期间）数据，以下是我的成绩单：

姓名	编号	总分	rps	link	bird	wireless	road	equation
李志锐	SD-1331	160	60	0	0	70	0	30

**Comment by nocrizwang** [comment]
对不起，数据策略是和noi.cn完全保持一致。
