### ISSUE TITLE
请求合并相同的学校

### ISSUE THREAD

**Issue by nuo0930** [nocrizwang/OIer#138]
rt
[北京市海淀区花园村第二小学](https://bytew.net/OIer/school.html?schoolid=758388257)、[北京市海淀区花园村第二小学花园村校区](https://bytew.net/OIer/school.html?schoolid=248156831)和[花园村第二小学](https://bytew.net/OIer/school.html?schoolid=273266313)。
这三个一看就知道同一所学校。。。只不过我到现在也没搞明白我们学校到底应该是叫啥。。。反正我参加的这三年，每年变一次。。。我也是服了。。。

**Comment by nuo0930** [comment]
还有[这个](https://bytew.net/OIer/school.html?schoolid=758388257)也是。。。

**Comment by nuo0930** [comment]
请问这是合并成功了吗？但是我这里看好像还没有啊

**Comment by TSStudio** [comment]
> 请问这是合并成功了吗？但是我这里看好像还没有啊

并不会立刻生效，要等待一段时间。另外建议报名的时候以学校公章为准

**Comment by nuo0930** [comment]
> > 请问这是合并成功了吗？但是我这里看好像还没有啊
> 
> 并不会立刻生效，要等待一段时间。另外建议报名的时候以学校公章为准

az，但是听我妈说报名时的名称是不能自己填，只能选择CCF给的那些名称。。。
