### ISSUE TITLE
需要帮助：PHP代码审核

### ISSUE THREAD

**Issue by nocrizwang** [nocrizwang/OIer#14]
感觉自己PHP写的很挫，经验也太少了。希望有一个大佬来帮忙看一下，来提一些意见，指出一些问题。

**Comment by xiekeyi98** [comment]
可以尝试使用一些 Github ~~官方~~的服务来辅助您，包括但不限于：
- https://github.com/marketplace/better-code-hub
- https://github.com/marketplace/lgtm
- https://github.com/marketplace/codebeat
