### ISSUE TITLE
学校合并错误

### ISSUE THREAD

**Issue by regooma** [nocrizwang/OIer#142]
南方科技大学附属中学不是深圳大学附属中学的别名，是一所独立高中，麻烦调整，谢谢~

**Comment by regooma** [comment]
![image](https://user-images.githubusercontent.com/18507042/144059631-fb572919-5fb5-42e9-a165-2db6d080d99d.png)

**Comment by nocrizwang** [comment]
@yhx-12243  现在webhook设置好了。
