### ISSUE TITLE
issue关了，可是错误没有修正

### ISSUE THREAD

**Issue by SteveSWang47** [nocrizwang/OIer#143]
[这个issue](https://github.com/OIerDb-ng/OIer/issues/141)关了，可是还是错的，一切问题都没有解决。

![](https://raw.githubusercontent.com/SteveSWang47/tmp/main/w.png)

**Comment by yhx-12243** [comment]
应该是没有同步，[oierdb-ng](http://82.157.186.142/oierdb-ng) 上是正确的。

![demo](https://i.loli.net/2021/12/03/xTXjsA8UYWJnaPZ.png)
