### ISSUE TITLE
OIerDB已经更新了NOIP2021，git还木有commit吗

### ISSUE THREAD

**Issue by kkksc03** [nocrizwang/OIer#145]
rt

**Comment by yhx-12243** [comment]
见 https://github.com/OIerDb-ng/OIer/commit/9c4e1808c72c142263102d47cc946b5a9c882639 。

**Comment by HappyCodeHC** [comment]
qp & 本人没考 noip & lg 用户名：HappyCode & 感觉是要导入奖项认证

**Comment by nocrizwang** [comment]
> rt

现在数据都在oierdb-ng分支上。
