### ISSUE TITLE
学校更名&选手合并

### ISSUE THREAD

**Issue by AccRobin** [nocrizwang/OIer#152]
## 学校更名

“西工大附中分校”（uid:45）应更名为“西北工业大学附属中学”。

## 选手合并

- 合并“潘逸飞”（uid:73940）和“潘逸飞”（uid:139052），后者应合并到前者，二者为同一人且年级应为高二。

- 合并“龚熙尧”（uid:51858）和“龚熙尧”（uid:139074），后者应合并到前者，二者为同一人且年级应为高二。

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
