### ISSUE TITLE
学校合并错误

### ISSUE THREAD

**Issue by sparrowhe** [nocrizwang/OIer#153]
![](https://user-images.githubusercontent.com/26871028/179507219-d847acd8-bac0-41b3-91ea-fa07769b0038.png)

济宁市第一中学与曲阜市实验中学是两个不同的学校

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
