### ISSUE TITLE
关于开盒

### ISSUE THREAD

**Issue by Ikaleio** [nocrizwang/OIer#156]
能不能禁止自己的数据被收录进OIerDB
基于名字首字母查询的功能为“开盒”提供了极大的便利
只要知道首字母和年级一般就能确定真实姓名和学校

**Comment by nocrizwang** [comment]
把你删了，马上就有人开发个网站统计谁被删了，你更被开盒

**Comment by TSStudio** [comment]
1）直接在git里删：git commit记录一查就看到你了，寄。
2）在程序层面，利用网站数据库屏蔽：名字三个字26^3在万量级，几分钟爬虫就能爬完，和git里的名单一比对，寄。

**Comment by henrytbtrue** [comment]
可能的解决方法：关闭名字首字母查询功能

**Comment by nocrizwang** [comment]
> 可能的解决方法：关闭名字首字母查询功能

关闭了，马上有人搞个没关闭的版本，所有人涌过去用那个版本
