### ISSUE TITLE
年级错误+合并选手

### ISSUE THREAD

**Issue by Kevin114514** [nocrizwang/OIer#157]
139766和82575实际上是一个人（就是我）
但是因为年级的问题导致分成了两个（？
请求合并/dk

**Comment by yhx-12243** [comment]
被误分裂的原因应该是（原始数据中）年级填写有误？请问你的初中入学年份是 2021（现在初一升初二）还是 2020（现在初二升初三），我们将根据情况进行修改。

**Comment by Kevin114514** [comment]
> 被误分裂的原因应该是（原始数据中）年级填写有误？请问你的初中入学年份是 2021（现在初一升初二）还是 2020（现在初二升初三），我们将根据情况进行修改。

是初一升初二
