### ISSUE TITLE
信息有误

### ISSUE THREAD

**Issue by Isonan-cn** [nocrizwang/OIer#16]
您好，您把我的信息与另一名同名者放在一起了：
本人胡杨，浙江人，OIerDB上却显示为 浙江/安徽，应是把我与一名来自安徽，同样名为胡杨的OIer当作一个人了。
希望及时修改。

**Comment by nocrizwang** [comment]
谢谢你的提醒，我会修改的。
这两天就会用规则强制分开，合并器会稍晚一些进行调整。

**Comment by nocrizwang** [comment]
(修复完成)

**Comment by nocrizwang** [comment]
假了啊没完成

**Comment by anycodes** [comment]
我为啥会莫名其妙收到这个邮件？。。

**Comment by nocrizwang** [comment]
你watch了这个repo，你可以选择不watch或者mute the thread，就收不到了

**Comment by Isonan-cn** [comment]
老哥都半年了。。。能不能麻烦改一下

**Comment by TOMWT-qwq** [comment]
![image](https://user-images.githubusercontent.com/49341906/62007697-24ef3780-b183-11e9-8a01-ec25fd0db2a1.png)
