### ISSUE TITLE
无法正确获取选手学校

### ISSUE THREAD

**Issue by jifbt** [nocrizwang/OIer#161]
在 OIerDB NG 上，所有选手的学校均变成 [长沙市雅礼中学](https://oier.baoshuo.dev/school/0)。

在 OIerDB 上，所有功能均无法使用。

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Minecrafl** [comment]
这边也是这样子

**Comment by jifbt** [comment]
现在好了，应该是服务器挂了
