### ISSUE TITLE
我是zcq,不是zzq

### ISSUE THREAD

**Issue by Hope2075** [nocrizwang/OIer#18]
为什么搜zcq找不到我，搜zzq就能找到我

姓名：左传奇

**Comment by nocrizwang** [comment]
大概是多音字识别挂了……
这个问题有了很长时间了，之后会看看怎么修复一下

**Comment by BeautyyuYanli** [comment]
说明您和zzq一样巨

**Comment by gcgeng** [comment]
这个问题是无解的吧...名字里的多音字怎么念并没有固定的标准啊....

**Comment by xjzsq** [comment]
> 为什么搜zcq找不到我，搜zzq就能找到我
> 
> 姓名：左传奇

惊现左传奇大佬！

**Comment by nocrizwang** [comment]
修了
