### ISSUE TITLE
关于一位选手的初/高中记录没有被合并

### ISSUE THREAD

**Issue by nishikinocurtis** [nocrizwang/OIer#24]
在数据库中，选手“高义雄”(河北)的初中和高中获奖记录没有被合并，建议合并。(我不是高义雄)

**Comment by anycodes** [comment]
这是啥，我为啥会收到邮件。。。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Curtis Nishikino "<notifications@github.com>;
发送时间：2019年3月1日(星期五) 中午1:19
收件人："WZKSDN/OIer" <OIer@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[WZKSDN/OIer] 关于一位选手的初/高中记录没有被合并 (#24)
-----------------------------------

 
在数据库中，选手“高义雄”(河北)的初中和高中获奖记录没有被合并，建议合并。(我不是高义雄)

**Comment by comld** [comment]
这是啥，我咋没收到邮件。。。

**Comment by SGColin** [comment]
这是啥，我也想收到邮件。。。

**Comment by nishikinocurtis** [comment]
这是啥，现在您们都该收到邮件了。。。

**Comment by Siyuanwww** [comment]
@WZKSDN 数据库中选手“刘淇中”的成绩也没有合并，建议合并。

**Comment by HeartyYF** [comment]
数据库中选手“杨懋龙”的成绩也没有合并
~~队长震怒（大嘘~~

**Comment by nocrizwang** [comment]
此问题已被解决
