### ISSUE TITLE
大佬可以考虑一下使用二级域名

### ISSUE THREAD

**Issue by Kutinana** [nocrizwang/OIer#26]
RT，就是oier.bytew.net的格式。
另外我可以提供直接的服务器捐助，只不过线路肯定没有您香港直连的好，是CN2GIA的，配置还看得过去。而且香港服务器容易被打，大佬小心，蒟蒻就稍微一提，相信大佬早已考虑到，在下就不多言了。【滑稽】

**Comment by abc1763613206** [comment]
主要是数据文件大吧，或许我可以提供一下国内备案服务器的缓存

在 2019-03-31 17:47:42，"Twilight Zhu" <notifications@github.com> 写道：


RT，就是oier.bytew.net的格式。
另外我可以提供直接的服务器捐助，只不过线路肯定没有您香港直连的好，是CN2GIA的，配置还看得过去。而且香港服务器容易被打，大佬小心，蒟蒻就稍微一提，相信大佬早已考虑到，在下就不多言了。【滑稽】
