### ISSUE TITLE
更改我的数据

### ISSUE THREAD

**Issue by william-song-shy** [nocrizwang/OIer#30]
![image](https://user-images.githubusercontent.com/47596959/57456189-7f24de80-729f-11e9-852a-7005cb5db3e5.png)
不少类似这样的问题，我分明是五年级，为什么说我六年级？

**Comment by william-song-shy** [comment]
![EgzAyQ.png](https://s2.ax1x.com/2019/05/09/EgzAyQ.png)
照片

**Comment by By-Ha** [comment]
先orz

**Comment by william-song-shy** [comment]
我菜死了


---原始邮件---
发件人: &quot;ByHa&quot;<notifications@github.com&gt;
发送时间: 2019年9月4日(星期三) 下午4:41
收件人: &quot;WZKSDN/OIer&quot;<OIer@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;william-song-shy&quot;<2560814258@qq.com&gt;;
主题: Re: [WZKSDN/OIer] 更改我的数据 (#30)



先orz
 
&mdash;

**Comment by By-Ha** [comment]
My vegetable exploded.



------------------ Original ------------------

**Comment by Charlie-zzy** [comment]
My vegetable dead.

**Comment by nocrizwang** [comment]
此问题已不再存在
