### ISSUE TITLE
为什么不把服务放在国内呢

### ISSUE THREAD

**Issue by Alan-yhq** [nocrizwang/OIer#31]

**Comment by PersicaMoe** [comment]
国内要备案吧，可能比较麻烦

**Comment by anycodes** [comment]
这是啥，我为啥总能收到邮件，我没订阅啊…

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："PersicaMoe "<notifications@github.com>;
发送时间：2019年7月11日(星期四) 下午3:22
收件人："WZKSDN/OIer" <OIer@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：Re: [WZKSDN/OIer] 为什么不把服务放在国内呢 (#31)
-----------------------------------

 
国内要备案吧，可能比较麻烦

**Comment by cms42** [comment]
很多国外VPS都比国内便宜，还不用备案

**Comment by nocrizwang** [comment]
懒得备案了，而且vultr还不错。
