### ISSUE TITLE
为什么不用去中心化服务器呢

### ISSUE THREAD

**Issue by cms42** [nocrizwang/OIer#33]
RT，可以考虑一下ZeroNet

**Comment by cms42** [comment]
如果数据库太大可以扔在IPFS或者COS(对象储存)上，甚至可以利用Amazon Lambda或者Azure Function进行搜索(反正免费配额多得是)，在公有云上完成本地检索，那么可以大大减小中心化模型的服务器负载或者是去中心化模型中的网络流量、磁盘占用

**Comment by anycodes** [comment]
强烈推荐腾讯云。使用https，可以不用备案。cos cdb scf加一个apigw就可以搞定整个项目。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："cms42 "<notifications@github.com>;
发送时间：2019年7月23日(星期二) 晚上10:20
收件人："WZKSDN/OIer" <OIer@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：Re: [WZKSDN/OIer] 为什么不用去中心化服务器呢 (#33)
-----------------------------------

 
如果数据库太大可以扔在IPFS或者COS(对象储存)上，甚至可以利用Amazon Lambda或者Azure Function进行搜索(反正免费配额多得是)，在公有云上完成本地检索，那么可以大大减小中心化模型的服务器负载或者是去中心化模型中的网络流量、磁盘占用

**Comment by frankli0324** [comment]
我来帮作者列一个供参考的简易roadmap吧（

1. 整理合并脚本，基本做到有新数据时只需要“添加数据源”即可，去除仓库中的数据
1. 统一语言，将合并逻辑与页面展示逻辑合并为同一个app，学习使用flask(python)（仅供参考）
1. 学习函数计算使用方式，并完全重构项目

去中心化的话。。的确感觉duck不必

**Comment by nocrizwang** [comment]
> 我来帮作者列一个供参考的简易roadmap吧（
> 
> 1. 整理合并脚本，基本做到有新数据时只需要“添加数据源”即可，去除仓库中的数据
> 2. 统一语言，将合并逻辑与页面展示逻辑合并为同一个app，学习使用flask(python)（仅供参考）
> 3. 学习函数计算使用方式，并完全重构项目
> 
> 去中心化的话。。的确感觉duck不必

草，这都一年多了吗？

**Comment by nocrizwang** [comment]
老了
