### ISSUE TITLE
您为啥不搞个SSL证书呢

### ISSUE THREAD

**Issue by cms42** [nocrizwang/OIer#34]
RT,为何不将自签发证书换成Let's Encrypt之类的免费SSL证书呢

**Comment by anycodes** [comment]
腾讯云有免费的，可以无限续签

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："cms42 "<notifications@github.com>;
发送时间：2019年7月23日(星期二) 晚上10:23
收件人："WZKSDN/OIer" <OIer@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[WZKSDN/OIer] 您为啥不搞个SSL证书呢 (#34)
-----------------------------------

 
RT,为何不将自签发证书换成Let's Encrypt之类的免费SSL证书呢

**Comment by nocrizwang** [comment]
现在或许好了，您试试？

**Comment by TOMWT-qwq** [comment]
qwq?怎么老是发邮件
