### ISSUE TITLE
致谢

### ISSUE THREAD

**Issue by kkksc03** [nocrizwang/OIer#37]
感谢这个项目。我们使用这个数据用于洛谷用户的实名奖项认证，并享有差异化的权限。

献上小小的一点捐助心意，希望oierdb能坚持下去。

**Comment by nocrizwang** [comment]
感谢洛谷做出的巨大捐助，祝洛谷越办越好。

**Comment by ciwomuli** [comment]
kkk真人

**Comment by ciwomuli** [comment]
好奇问一下，省一会获得什么权限

**Comment by nocrizwang** [comment]
Issue Closed
