### ISSUE TITLE
代码的格式化

### ISSUE THREAD

**Issue by frankli0324** [nocrizwang/OIer#46]
大佬做的工作的确nb
但是我还是忍不住想说一下。。。好歹拿什么编辑器格式化一下代码撒。。
inconsistent use of tabs and spaces警告
![image](https://user-images.githubusercontent.com/20221896/68137835-94cf4400-ff62-11e9-938a-d483962330dc.png)

抑制住了我丢下自己的事水PR的冲动.jpg

**Comment by frankli0324** [comment]
可以封装一些东西，比如
```php
function get_sql_connection() {
	...
	return $conn;
}
```
对于变量的拼接
```php
function concat_if_set($s, $variable) {
	if(isset($variable)){
		// maybe some WAF?
		$s .= mysqli_real_escape_string($conn, $variable);
	}
	return $s;
}
```

像
```php
error_reporting(0);
header("Access-Control-Allow-Origin: http://www.bytew.net");
```
这些东西也都可以单独放在一个文件里，然后在每个文件include一遍

**Comment by TSStudio** [comment]
> 可以封装一些东西，比如
> 
> ```php
> 
> function get_sql_connection() {
> 
> 	...
> 
> 	return $conn;
> 
> }
> 
> ```
> 
> 对于变量的拼接
> 
> ```php
> 
> function concat_if_set($s, $variable) {
> 
> 	if(isset($variable)){
> 
> 		// maybe some WAF?
> 
> 		$s .= mysqli_real_escape_string($conn, $variable);
> 
> 	}
> 
> 	return $s;
> 
> }
> 
> ```
> 
> 
> 
> 像
> 
> ```php
> 
> error_reporting(0);
> 
> header("Access-Control-Allow-Origin: http://www.bytew.net");
> 
> ```
> 
> 这些东西也都可以单独放在一个文件里，然后在每个文件include一遍
> 
> 

php的include占用大量IO，多一个include就多一个IO。这种短代码反而不适合include

**Comment by frankli0324** [comment]
首先，这19年的issue了
其次，我不知道你概念中的“大量IO”是从何而来的，如何“量化”的。
照这么说，世界上那么多的框架，那么多的CMS都是白写了，composer构建起一个php程序包含文件的次数超乎你想象。
就程序而言，你这程序远没有到需要考虑“include会占用IO”这种问题的时候。
就完成工作而言，我敬你是条汉子，就代码而言，唉
