### ISSUE TITLE
一个顶俩

### ISSUE THREAD

**Issue by skylee03** [nocrizwang/OIer#48]
![](https://i.loli.net/2019/11/30/MB7pDhzCI9GKTfr.png)

**Comment by code004Accepted** [comment]
@skylee03 

![](http://camo.githubusercontent.com/cd4079711ce9de3dba94eb7ae143a1b9c3f81f70/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f33302f4d42377044687a434939474b5466722e706e67)

图炸了qwq

**Comment by skylee03** [comment]
> @skylee03
> 
> ![](http://camo.githubusercontent.com/cd4079711ce9de3dba94eb7ae143a1b9c3f81f70/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f33302f4d42377044687a434939474b5466722e706e67)
> 
> 图炸了qwq

没有吧

@q234rty

**Comment by code004Accepted** [comment]
没有（

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
