### ISSUE TITLE
社会人士信息需合并

### ISSUE THREAD

**Issue by duhao110101** [nocrizwang/OIer#50]
如我自己：杜昊

搜出来的两个信息实际为同一人，在高中毕业后（其实是大学毕业工作后）以社会人士身份参与了今年的比赛

类似情况应该还有一些，建议合并

**Comment by nocrizwang** [comment]
情况已知晓，最早同CSP二等奖一同更新

**Comment by kkksc03** [comment]
这个挺难的，有的省份也变了，有的时隔很久，除了同名以外就没有别的线索了。

**Comment by duhao110101** [comment]
这倒是，不过目前来看，这几个少数的应该还是判断的出来对应的原 OI 选手具体是谁的，不过仅限于少量数据，数据量大了之后就没办法了

**Comment by nocrizwang** [comment]
暂时将你合并了，但是此问题没有得到解决
