### ISSUE TITLE
学校信息有误

### ISSUE THREAD

**Issue by rikukiix** [nocrizwang/OIer#55]
![bug](https://user-images.githubusercontent.com/52599939/70843015-38ffb100-1e66-11ea-8899-f967383935d5.png)

“辽宁省实验中学”，“辽宁省实验学校”为位于辽宁省沈阳市的两个不同学校且与位于河南省的“河南省实验中学”没有任何关系。

**Comment by lavacup2233** [comment]
已经反馈过了，群主说这周没空要下周。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nocrizwang** [comment]
今天修
