### ISSUE TITLE
CSP 2019 获奖名单更新

### ISSUE THREAD

**Issue by ouuan** [nocrizwang/OIer#58]
申诉后的获奖名单已在 <http://www.noi.cn/newsview.html?id=1159&hash=C6E66B&type=8> 公布。

例如：钱易申诉后 600 分。

**Comment by nocrizwang** [comment]
orz，我知道了
您要不要试试把它整下来整成data.txt里的格式？
或者写个脚本搞一下。。
或者有时间我搞。。。
