### ISSUE TITLE
NOI Online 能力测试

### ISSUE THREAD

**Issue by DeCalvin2006** [nocrizwang/OIer#59]
[NOI原文](http://www.noi.cn/newsview.html?id=1174&hash=BBB849)

这个比赛结束，成绩要整理到OierDB上吗

**Comment by DeCalvin2006** [comment]
再说一句

# __我是初一现役OIer__

**Comment by DeCalvin2006** [comment]
@WZKSDN

**Comment by nocrizwang** [comment]
如果[这里](http://www.noi.cn/awardsearch.html) 上收录了，就收录
