### ISSUE TITLE
rank.html代码太乱

### ISSUE THREAD

**Issue by panda2134** [nocrizwang/OIer#62]
大概不算一个issue?
总之就是代码里面html和js混着写，而且大量直接修改`innerHTML`很不方便维护
可以考虑用 UI 库 / WebComponent 重构，以提高可维护性

**Comment by nocrizwang** [comment]
草，都是高一时候写的

**Comment by nocrizwang** [comment]
麻了。这个项目活到yhx的项目把所有的用户吸引过去就可以不活了。

@yhx-12243 你要加油
