### ISSUE TITLE
第三方拼音库漏洞百出

### ISSUE THREAD

**Issue by yhx-12243** [nocrizwang/OIer#67]
经过检查，目前 OIerDb 使用的 `xpinyin` 库存在很多拼音错误问题，目前共找出 21 处 (不考虑多音字的常识性错误)：

result.csv 中的编号 | 姓名 | result.csv 中的拼音 | 正确拼音
-- | -- | -- | --
241 | 陈栉旷 | cjk | czk
5280 | 杨子烆 | yzx | yzh
9326 | 徐恺钖 | xkx | xky
11934 | 邓褀麟 | djl | dql
15930 | 陈泺嘉 | cbj | clj \| cpj
16034 | 呙雅歌 | kyg | gyg
16450 | 张泺陶 | zbt | zlt \| zpt
17033 | 沈锘遥 | sty | sny
17141 | 刘垭畅 | lwc | lyc
19119 | 闫锗渊 | ydy | yzy
19995 | 范钶 | fe | fk
20534 | 呙荸帏 | kbw | gbw
29202 | 唐沥钖 | tlx | tly
30745 | 呙欣 | kx | gx
34194 | 党泺洋 | dby | dly \| dpy
36201 | 査卉妍 | chy | zhy
42031 | 景锗敏 | jdm | jzm
43886 | 査盛轶 | csy | zsy
44943 | 徐俍锘 | xlt | xln
45689 | 万宗褀 | wzj | wzq
45994 | 林子褀 | lzj | lzq

希望能换一个更好的拼音处理库。

**Comment by nocrizwang** [comment]
orz 您说的对 但是xpinyin也是一个更差的换过来的……我想想办法。

**Comment by Anguei** [comment]
还有 yanQcal（

**Comment by yhx-12243** [comment]
> 还有 yanQcal（

像“乾”这种多音字还说的过去，但像“栉”读成 jie 一些根本不存在的读音应该先避免 /cy

**Comment by nocrizwang** [comment]
应该解决了
