### ISSUE TITLE
WC2020的某些选手获奖记录需要合并

### ISSUE THREAD

**Issue by loader3229** [nocrizwang/OIer#69]
WC2020的某些选手填写年级时填写了暑假后的年级，在oierdb里面被处理成暑假前的年级，导致不能自动合并选手（例如我搜索自己会出现两个，其中一个只有WC2020的获奖记录）

**Comment by samxiaocd** [comment]
这个问题似乎只有人工一个个地检查了，有的人填的是暑假前的年级，有的人填的是暑假后的年级

**Comment by nocrizwang** [comment]
有问题直接改，pull request
