### ISSUE TITLE
我想搭一个玩可是我太菜了不会导入数据到MySQL

### ISSUE THREAD

**Issue by dishangti** [nocrizwang/OIer#72]
RT，很想搭一个玩，PHP+Nginx和MySQL已经装好了，但是不知道怎么把那个csv文件导入mysql，主要是不知道新建数据表应该怎么设置属性。

**Comment by samxiaocd** [comment]
我用两天时间在WAMP中部署了一个，记录于下：
[OIerDb在WAMP环境中部署记录 ](https://mp.weixin.qq.com/s?__biz=Mzg5MTU0NzgwMQ==&mid=2247483673&idx=1&sn=8461f741855d2950a2a59a2bb16e4ee4&chksm=cfcaf8eff8bd71f97d3e16439324f4e67fe07b342f17983fcaa168350d7ecb2c728b55016745&mpshare=1&scene=23&srcid=1213MCH2kADmjPMNibojO1zP&sharer_sharetime=1607858710883&sharer_shareid=5aa7a3cb30d1aa5f9a9f99d9383358ce#rd)
看看能否解决你的问题

**Comment by nocrizwang** [comment]
等我写个自动部署脚本。事实上，自动生成数据并把数据导入数据库的脚本已经写好了。。

**Comment by dishangti** [comment]
emmm好的非常感谢

> 我用两天时间在WAMP中部署了一个，记录于下：
> [OIerDb在WAMP环境中部署记录 ](https://mp.weixin.qq.com/s?__biz=Mzg5MTU0NzgwMQ==&mid=2247483673&idx=1&sn=8461f741855d2950a2a59a2bb16e4ee4&chksm=cfcaf8eff8bd71f97d3e16439324f4e67fe07b342f17983fcaa168350d7ecb2c728b55016745&mpshare=1&scene=23&srcid=1213MCH2kADmjPMNibojO1zP&sharer_sharetime=1607858710883&sharer_shareid=5aa7a3cb30d1aa5f9a9f99d9383358ce#rd)
> 看看能否解决你的问题

**Comment by nocrizwang** [comment]
import os,pymysql
import csv
import pandas as pd
from sqlalchemy import create_engine, types

os.system("rm -r OIer")
os.system("git clone https://github.com/nocrizwang/OIer")
os.system("mv OIer/model/* .")
os.system("python3 new_merger.py")
os.system("python3 school_analyzer.py")

engine = create_engine('mysql+pymysql://root:password@localhost/OIerDb?charset=utf8')

engine.execute("TRUNCATE OIers")
df = pd.read_csv("result.csv",sep=',',quotechar='"')
df.to_sql('OIers',con=engine,if_exists='append', index= False)

engine.execute("TRUNCATE OI_school")
df = pd.read_csv("school_data.csv",sep=',',quotechar='"')
df.to_sql('OI_school',con=engine,if_exists='append', index= False)
