### ISSUE TITLE
一个历年 noip 二等三等奖名单收集的建议

### ISSUE THREAD

**Issue by wph95** [nocrizwang/OIer#75]
可以从各地的xiaoxiaotong 获得到历年的参赛选手复赛成绩和奖项
以浙江为例
- noip 2012 所有选手成绩公示 http://zhejiang.xiaoxiaotong.org/FileNotice/Detail?lnArticleID=18514 
- noip 2012 浙江赛区一二三等奖公示 http://zhejiang.xiaoxiaotong.org/FileNotice/Detail?lnArticleID=18671

**Comment by nocrizwang** [comment]
难度比较大啊。。
