### ISSUE TITLE
学校合并错误

### ISSUE THREAD

**Issue by mcqueen-ren** [nocrizwang/OIer#78]
“南京师范大学附属中学江宁分校”与“东北师范大学附属中学”没有任何关系 （这两个学校甚至不是一个省的）

![](https://cdn.luogu.com.cn/upload/image_hosting/4zvfy02g.png)

**Comment by mcqueen-ren** [comment]
https://cdn.luogu.com.cn/upload/image_hosting/4zvfy02g.png 图片

**Comment by TSStudio** [comment]
Solved in #77
已在 #77 中解决
