### ISSUE TITLE
选手合并错误

### ISSUE THREAD

**Issue by ignited-cn** [nocrizwang/OIer#84]
在界面输入“陈诺”，第二个人的NOIP2020一等奖（191pts）和CSP2020提高二等奖（150pts）的获奖记录和第三个人的CSP2019提高组二等奖（144）是我一个人的记录。望合并！
就是先树人学校再扬州中学

**Comment by samxiaocd** [comment]
@ignited-cn  下面三条是同你一个人的？ 

获奖 | 分数 | 全国排名 | 就读学校 | 年级
-- | -- | -- | -- | --
NOIP2020一等奖   	|191	|576	|江苏省扬州中学 	|高一
CSP2020提高二等奖	|150	|2061	|江苏省扬州中学	    |高一


CSP2019提高二等奖 | 144 | 5067 | 扬州中学教育集团树人学校 | 初二
-- | -- | -- | -- | --


CSP2019年级是初二，今年高一，是跳级了还是去年或今年的年级不对？

**Comment by samxiaocd** [comment]
已在我的新的PR中修正了这个错误，通过加后缀的方法。

**Comment by nocrizwang** [comment]
此问题已不存在
